users/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash , session, abort
from flask_login import login_user, login_required, logout_user, current_user
from flask_bcrypt import Bcrypt
from users.forms import LoginForm, RegistrationForm, updateStatus
from model import User, Job, UserJob, db
from crud import update_favorite_job

bcrypt = Bcrypt()

users_blueprint = Blueprint('users', __name__, template_folder='templates/users')

@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    flash('You logged out!')
    return redirect(url_for('home'))


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('Logged in successfully!', 'success')
            next_url = request.args.get('next')
            if next_url and next_url.startswith('/'):
                return redirect(next_url)
            return redirect(url_for('home'))
        else:
            flash('Invalid email or password. Please try again.', 'error')
    return render_template('login.html', form=form)
    

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user_check = User.query.filter_by(email=form.email.data).first()

        if not user_check:
            user = User(username=form.username.data,
                        email=form.email.data,
                        password=form.password.data)

            db.session.add(user)
            db.session.commit()
            flash('Thanks for registration!')
            return redirect(url_for('users.login'))
        else:
            flash('This email has already been taken')

    return render_template('register.html', form=form)


@users_blueprint.route('/my_jobs', methods = ['GET', 'POST'])
def my_jobs():
    page = request.args.get('page', 1, type=int)
    per_page = 10

    user_id = current_user.get_id()
    saved_jobs = UserJob.query.filter_by(user_id=user_id).paginate(page=page, per_page=per_page)
    job_results = []

    sort_option = request.args.get('sort')
    if sort_option == 'recent':
        saved_jobs_query = UserJob.query.filter_by(user_id=user_id).order_by(UserJob.last_modified.desc())
    elif sort_option == 'status':
        saved_jobs_query = UserJob.query.filter_by(user_id=user_id).order_by(UserJob.status)

    for job in saved_jobs:
        job_result = Job.query.filter_by(id=job.job_result_id).first()
        job_results.append((job_result))

    form = updateStatus()

    if request.method == 'POST':
        if form.validate_on_submit():
            job_id = request.form.get('job_id')
            update_favorite_job(user_id, job_id, form.status.data)

            for field, errors in form.errors.items():
                for error in errors:
                    print(f"Field '{field}': {error}")
    return render_template('my_jobs.html', form=form, job_results=job_results, saved_jobs=saved_jobs, sort_option=sort_option)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles.css') }}"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">

<!-- GOOGLE FONTS -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mali:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
<!-- GOOGLE FONTS -->
      
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="loader"></div>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container-fluid">
        {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="#">Welcome {{current_user.username}}, Happy Hunting</a>
        {{current_user.username}}
        {% else %}
        <a class="navbar-brand" href="#">Happy Hunting</a>
        {% endif %}
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('home')}}">Search</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.my_jobs')}}">My Jobs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
        </div>
          <div class="navbar-nav"></div>
        </div>
      </div>
    </nav>
    
      <div class="main-container">{% block content %} {% endblock %}</div>
      <div class="container">{% block after_content %}{% endblock %}</div>
    
    <script>
      window.addEventListener("load", () => {
        const loader = document.querySelector(".loader")
        loader.classList.add("loader-hidden")
        loader.addEventListener("transitionend", () => {document.body.removeChild("loader")})
      })
    </script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="search-image row align-items-center">
  <div class="container position-relative text-center text-white">
    <h1 class="fst-bold p-4">JobSearch Solutions</h1>
    <div class="d-flex flex-row justify-content-center p-2">
      <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="input-group d-flex justify-content-center">
          {{ form.search_term(class="form-control") }} {{
          form.search_location(class="form-control") }} {{
          form.search_radius(class="form-control") }} {{ form.submit(class="btn
          btn-primary d-flex justify-content-center search_btn") }}
        </div>
      </form>
    </div>
    {% if current_user.is_authenticated %} {% else %}
    <p class="fst-italic">*Login or Register to Save to Favorites!</p>
    {% endif %}
  </div>
</div>
{% endblock %} {% block after_content %}
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const submitButton = document.querySelector(".search_btn");
    submitButton.addEventListener("click", () => {
      const searchTerm = document.querySelector("#search_term").value.trim();
      const searchLocation = document
        .querySelector("#search_location")
        .value.trim();
      const searchRadius = document
        .querySelector("#search_radius")
        .value.trim();

      if (searchTerm !== "" && searchLocation !== "" && searchRadius !== "") {
        const loader = document.querySelector(".loader");
        loader.classList.remove("loader-hidden");
      } else {
        alert("Please fill in all fields before searching.");
      }
    });
  });
</script>
{% endblock %}

templates/results.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron container-fluid text-center align-items-center">
  <h3>Search Results</h3>
  <br />
  <table id="data" class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Company</th>
        <th>Location</th>
        <th>Salary</th>
        <th>Description</th>
        <th>Favorites</th>
      </tr>
    </thead>
    <tbody>
      {% for result in results %}
      <tr>
        <td>
          <a class="results-link" href="{{ result.url }}">{{ result.title }}</a>
        </td>
        <td>{{ result.company }}</td>
        <td>{{ result.location }}</td>
        <td>{{ result.salary }}</td>
        <td>{{ result.description }}</td>
        <td>
          <div class="form-check form-switch">
            <input
              class="form-check-input favorite-checkbox"
              type="checkbox"
              role="switch"
              data-result-id="{{ result.id }}"
              {%
              if
              result.favorite
              %}checked{%
              endif
              %}
            />
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="text-center">
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        <li class="page-item {% if not results.has_prev %}disabled{% endif %}">
          <a
            class="page-link"
            href="{{ url_for('view_results', search_term=search_term, page=results.prev_num) }}"
            aria-label="Previous"
          >
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% for page_num in results.iter_pages() %} {% if page_num %}
        <li
          class="page-item {% if page_num == results.page %}active{% endif %}"
        >
          <a
            class="page-link"
            href="{{ url_for('view_results', search_term=search_term, page=page_num) }}"
            >{{ page_num }}</a
          >
        </li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">...</span></li>
        {% endif %} {% endfor %}
        <li class="page-item {% if not results.has_next %}disabled{% endif %}">
          <a
            class="page-link"
            href="{{ url_for('view_results', search_term=search_term, page=results.next_num) }}"
            aria-label="Next"
          >
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const checkboxes = document.querySelectorAll(".favorite-checkbox");
    checkboxes.forEach((checkbox) => {
      checkbox.addEventListener("change", function () {
        const resultId = this.getAttribute("data-result-id");
        const isChecked = this.checked;

        console.log(resultId);

        fetch("/toggle_favorite", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            result_id: resultId,
          }),
        })
          .then((response) => {
            if (response.ok) {
              console.log("Favorite toggled successfully");
            } else {
              alert("Please log in to add favorites!");
              window.location.href = "/users/login";
            }
          })
          .catch((error) => {
            console.error("Error:", error);
          });
      });
    });
  });
</script>
{% endblock %}